name: Resuable workflow - Deployment

on:
  workflow_call: 
    secrets:
      K8S-KUBECONFIG:
        required: true
      MONGO-DB-PASSWORD:
        required: true
    inputs:
      MONGO_URI:
        required: true
        type: string
      KUBECTL_VERSION:
        description: Provide the required kubectl version
        required: false
        type: string
        default: v1.27.9
      K8S_MANIFEST_DIR:
        description: Directories containing manifest files
        required: true
        type: string
        default: kubernetes/
      ENVIRONMENT:
        description: Provide the deployment environment
        required: true
        type: string
        default: development
    outputs:
      APPLICATION_URI:
        value: ${{ jobs.reusable-deploy.outputs.APP_INGRESS_URL }}

jobs:
  reusable-deploy:
    
    runs-on: ubuntu-latest

    environment: 
      name: ${{ inputs.ENVIRONMENT }}
      url: https://${{ steps.ingress-host-id.outputs.APP_INGRESS_HOST }}

    outputs:
      APP_INGRESS_URL: ${{ steps.ingress-host-id.outputs.APP_INGRESS_HOST }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install kubectl cli
        uses: azure/setup-kubectl@v3
        with:
          version: '${{ inputs.KUBECTL_VERSION }}'

      - name: Kube login context - dev
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S-KUBECONFIG }}

      - name: Fetch Kubernetes cluster details - dev
        run: |
          kubectl version --short
          echo ----------------------------
          kubectl get nodes
          kubectl -n app-routing-system get service

      - name: Fetch NGINX Ingress IP and export it as a GitHub environment variable
        run: |
          echo "INGRESS_IP=$(kubectl -n ingress-nginx get service ingress-nginx-controller -o jsonpath="{.status.loadBalancer.ingress[0].ip}")" >> $GITHUB_ENV

      - name: Replace tokens in manifest files
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["${{ inputs.K8S_MANIFEST_DIR}}/${{ inputs.ENVIRONMENT }}/*.yaml"]'
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
          INGRESS_IP: ${{ env.INGRESS_IP }}

      - name: Check token replacement in files
        run: cat ${{ inputs.K8S_MANIFEST_DIR}}/${{ inputs.ENVIRONMENT }}/*.yaml

      - name: Create MongoDB secret
        run: |
          kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
          --from-literal=MONGO_URI=${{ inputs.MONGO_URI }} \
          --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
          --from-literal=MONGO_PASSWORD=${{ secrets.MONGO-DB-PASSWORD }} \
          --save-config \
          --dry-run=client \
          -o yaml | kubectl apply -f -

      - name: Deploy to Dev environment
        run: |
          kubectl apply -f ${{ inputs.K8S_MANIFEST_DIR}}/${{ inputs.ENVIRONMENT }}

      - name: Set App ingress host URL
        id: ingress-host-id
        run: |
          echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> $GITHUB_OUTPUT